spring.application.name=Board

# web page setting
server.servlet.context-path=/

# server port 변경
server.port=8080

# jsp 파일위치
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# jsp 서버 재시작 바로 적용
server.servlet.jsp.init-parameters.development=true

# mybatis 설정 (resources)
mybatis.mapper-locations=classpath:mapper/**/*Mapper.xml

# oracle db 연결
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=spring
spring.datasource.password=1234